name: KitPvp
version: 1.1
author: JBStudios
main: net.jbstudios.kitpvp.Manager
api-version: 1.16
commands:
    KP:
        permission: KP
        permission-message: You do not have permission!